import "@/app/globals.css";
import { Inter } from "next/font/google";
import Providers from "@/app/providers";
import { Toaster } from "@/components/ui/sonner";
import type { PropsWithChildren } from "react";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="pl" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <Providers>{children}</Providers>
        <Toaster
          position="bottom-right"
          // richColors
          // closeButton
          toastOptions={{ duration: 5000 }}
        />
      </body>
    </html>
  );
}
