import "@/app/globals.css";
import { Inter } from "next/font/google";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import { ThemeProvider } from "@/components/ThemeProvider";
import { UserStoreProvider } from "@/components/UserStoreProvider";
import { Toaster } from "@/components/ui/sonner";
import type { PropsWithChildren } from "react";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="pl" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <ReactQueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <UserStoreProvider>{children}</UserStoreProvider>
          </ThemeProvider>
        </ReactQueryProvider>
        <Toaster
          position="bottom-right"
          richColors
          closeButton
          toastOptions={{ duration: 5000 }}
        />
      </body>
    </html>
  );
}
